import { EmotionMeta, EmotionType, DiaryEntry } from '../types/diary';

export const EMOTIONS: Record<EmotionType, EmotionMeta> = {
  기쁨: {
    type: '기쁨',
    label: '기쁨',
    icon: '☀️',
    color: 'text-amber-600',
    bgColor: 'bg-amber-50 hover:bg-amber-100/80',
    borderColor: 'border-amber-300',
    badgeColor: 'bg-amber-100 text-amber-800 border-amber-300',
    description: '반짝이고 활기찬 오늘의 기쁨과 감사',
  },
  지침: {
    type: '지침',
    label: '지침',
    icon: '🌙',
    color: 'text-indigo-600',
    bgColor: 'bg-indigo-50 hover:bg-indigo-100/80',
    borderColor: 'border-indigo-300',
    badgeColor: 'bg-indigo-100 text-indigo-800 border-indigo-300',
    description: '온종일 수고 많았던 내 지친 몸과 마음',
  },
  설렘: {
    type: '설렘',
    label: '설렘',
    icon: '🌸',
    color: 'text-rose-600',
    bgColor: 'bg-rose-50 hover:bg-rose-100/80',
    borderColor: 'border-rose-300',
    badgeColor: 'bg-rose-100 text-rose-800 border-rose-300',
    description: '두근두근 피어오르는 기대와 설렘',
  },
  불안: {
    type: '불안',
    label: '불안',
    icon: '🍃',
    color: 'text-emerald-700',
    bgColor: 'bg-emerald-50 hover:bg-emerald-100/80',
    borderColor: 'border-emerald-300',
    badgeColor: 'bg-emerald-100 text-emerald-800 border-emerald-300',
    description: '마음이 서성이고 걱정이 밀려올 때',
  },
};

export const INITIAL_SAMPLE_DIARIES: DiaryEntry[] = [
  {
    id: 'sample-entry-1',
    date: '2026-09-30',
    createdAt: new Date(Date.now() - 86400000).toISOString(),
    title: '프로젝트 마감 후 깊은 안도감',
    emotion: '지침',
    emotionIntensity: 4,
    content: '[감사] 마감까지 함께 야근하며 든든하게 챙겨준 팀원들에게 감사했다.\n[다행 1] 준비한 시연 도중 오류 없이 무사히 마무리된 것\n[다행 2] 퇴근길에 막힘없이 빠르게 지하철을 타고 귀가한 것\n[선행] 지친 후배에게 따뜻한 밀크티를 건네며 수고했다고 토닥여준 일\n[그럼에도 다행] 온몸에 긴장이 풀려 녹초가 되었지만, 끝까지 도망치지 않고 완주한 내 자신을 칭찬할 수 있었던 점',
    structured: {
      exerciseName: '퇴근 후 저녁 가벼운 산책',
      exerciseDuration: '30분',
      exerciseFeeling: '바람을 쐬며 천천히 걸으니 긴장했던 목과 어깨가 한결 부드러워짐',
      moodTaste: '구수한',
      moodWeather: '화창한',
      gratitude: '마감까지 함께 야근하며 든든하게 챙겨준 팀원들에게 진심으로 감사했다.',
      relief1: '준비한 발표와 시연 도중 시스템 오류 없이 무사히 마무리된 것',
      relief2: '퇴근길에 막힘없이 빠르게 지하철을 타고 귀가한 것',
      kindness: '지친 후배에게 따뜻한 밀크티를 건네며 그동안 고생 많았다고 토닥여준 일',
      silverLining: '온몸에 긴장이 풀려 녹초가 되었지만, 끝까지 도망치지 않고 완주한 내 자신을 칭찬할 수 있었던 점',
      episodeTime: '오후 4시 프로젝트 최종 발표 직전',
      episodePlace: '본사 대회의실 앞 복도',
      episodePeople: '발표 순서를 기다리던 나와 동료들',
      episodeInnerFeeling: '심장이 터질 듯이 뛰고 손에 땀이 났다. 혹시 실수해서 팀에 폐를 끼치면 어쩌나 하는 불안과 부담감이 밀려왔다.',
      episodeEmotion: '불안',
      episodeActionTaken: '벽을 짚고 눈을 감은 채 심호흡을 세 번 크게 들이마시고, 준비했던 오프닝 멘트를 조용히 소리 내어 읊었다.',
      episodeFutureAction: '긴장될 때는 손을 가볍게 털고, 완벽하려는 욕심을 내려놓은 채 "진심을 전하자"라고 속으로 세 번 되뇌기',
    },
    cheer: {
      comfortingMessage: '그동안 무거운 책임감을 짊어지고 달리느라 정말 고생 많으셨어요. 긴장으로 심장이 뛰는 와중에도 심호흡을 하며 끝까지 자리를 지켜낸 당신의 용기는 참으로 눈부십니다. 후배에게 따뜻한 밀크티를 건네는 다정함까지 잃지 않은 당신에게 깊은 경의를 표해요. 오늘만큼은 세상 모든 부담을 내려놓고 가장 편안한 쉼을 누리세요.',
      tomorrowAction: '내일 아침에는 알람 소리 없이 10분만 더 침대에서 뒹굴거린 후, 어깨를 가볍게 돌려주며 기지개를 켜보세요.',
      vitaminQuote: '열심히 달려온 당신의 쉼은 게으름이 아니라, 내일을 위한 가장 아름다운 숨고르기입니다.',
      emotionAnalysis: '오랜 시간 팽팽했던 마음의 끈을 풀고 마침내 찾아온 평온한 지침과 안도',
      recommendedTea: '향긋한 캐모마일 티와 따뜻한 온수 샤워',
      keywordTag: '#그동안_정말_수고했어',
    },
    isActionCompleted: true,
  },
  {
    id: 'sample-entry-2',
    date: '2026-09-29',
    createdAt: new Date(Date.now() - 172800000).toISOString(),
    title: '새로운 취미를 시작한 날',
    emotion: '설렘',
    emotionIntensity: 5,
    content: '[감사] 퇴근길 노을이 유난히 예뻐서 지친 하루에 큰 위로가 되었다.\n[다행 1] 평소 배우고 싶었던 도예 원데이 클래스에 마지막 1자리가 남아 예약에 성공한 것\n[다행 2] 오늘 해야 할 업무를 정시에 깔끔하게 마무리한 것\n[선행] 지하철 계단에서 짐이 무거워 힘들어하시는 어르신의 카트를 들어드린 일\n[그럼에도 다행] 이번 주말 일정이 꽉 차 피곤할 수도 있지만, 새로운 배움으로 나를 채울 수 있다는 기대감이 차오른 점',
    structured: {
      exerciseName: '아침 모닝 요가 & 스트레칭',
      exerciseDuration: '25분',
      exerciseFeeling: '밤새 굳어 있던 척추와 골반이 시원하게 풀리고 상쾌하게 하루를 시작함',
      moodTaste: '달콤한',
      moodWeather: '포근한',
      gratitude: '퇴근길 노을이 유난히 붉고 예뻐서 지친 하루에 큰 위로를 주었다.',
      relief1: '배우고 싶었던 도예 원데이 클래스에 마지막 잔여 1자리가 남아 예약에 성공한 것',
      relief2: '오늘 밀려 있던 업무를 정시에 깔끔하게 마무리한 것',
      kindness: '지하철 계단에서 무거운 짐을 들고 계신 어르신의 손수레를 위까지 함께 들어드린 일',
      silverLining: '이번 주말 일정이 꽉 차 피곤할 수도 있지만, 새로운 도전으로 나를 가득 채울 수 있다는 기대감이 더 큰 점',
      episodeTime: '퇴근길 버스 정류장에서',
      episodePlace: '회사 앞 버스 정류장',
      episodePeople: '나 자신과 길을 걷던 사람들',
      episodeInnerFeeling: '매일 반복되는 일상에 무기력해지려던 찰나, 도예 클래스 신청 완료 알림을 보고 가슴이 콩닥거리며 몽글몽글한 행복이 차올랐다.',
      episodeEmotion: '설렘',
      episodeActionTaken: '평소에 눈여겨보았던 도자기 컵 사진들을 앨범에 저장하며 주말에 만들 모양을 상상했다.',
      episodeFutureAction: '일상에 권태감이 찾아올 때는 망설이지 말고 작은 원데이 클래스나 전시회처럼 나를 위한 작은 이벤트를 선물하기',
    },
    cheer: {
      comfortingMessage: '스스로에게 새로운 즐거움을 선물하는 용기가 정말 멋져요! 계단에서 어르신을 도와드린 따뜻한 선행과 퇴근길 노을을 눈에 담는 감수성까지, 당신의 오늘은 온통 반짝이는 보물들로 가득합니다. 그 설렘의 온도가 주말까지 기분 좋게 이어지길 바라요.',
      tomorrowAction: '내가 만들고 싶은 그릇의 모양이나 색감을 메모장에 1분 동안 가볍게 끄적여보세요.',
      vitaminQuote: '내가 나를 아껴줄 때, 삶은 가장 사랑스러운 빛깔로 물듭니다.',
      emotionAnalysis: '나를 향한 다정한 선물에서 피어난 맑고 순수한 설렘',
      recommendedTea: '달콤 상큼한 유자 히비스커스 티',
      keywordTag: '#두근거리는_새로운_시작',
    },
    isActionCompleted: false,
  },
];
